---
- name: Create the apps.dmlb2000.org/v1alpha1.Drupal
  k8s:
    state: present
    namespace: '{{ namespace }}'
    definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
    wait: yes
    wait_timeout: 300
    wait_condition:
      type: Running
      reason: Successful
      status: "True"
  vars:
    cr_file: 'apps_v1alpha1_drupal.yaml'
  register: drupal_sample_result

- name: Assert Drupal Sample was created
  assert:
    that:
      - drupal_sample_result.result.metadata.name == 'drupal-sample'
