---
- name: Create the apps.dmlb2000.org/v1alpha1.Drupal
  k8s:
    state: present
    namespace: '{{ namespace }}'
    definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
    wait: yes
    wait_timeout: 300
    wait_condition:
      type: Running
      reason: Successful
      status: "True"
  vars:
    cr_file: 'apps_v1alpha1_drupal.yaml'
  result: drupal_sample_result

- name: Debug drupal sample result
  debug:
    msg: "{{ drupal_sample_result }}"
