# permissions for end users to edit drupals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drupal-editor-role
rules:
- apiGroups:
  - apps.dmlb2000.org
  resources:
  - drupals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.dmlb2000.org
  resources:
  - drupals/status
  verbs:
  - get
