apiVersion: apps.dmlb2000.org/v1alpha1
kind: Drupal
metadata:
  name: drupal-sample-dev
spec:
    # The container image to use for the Drupal deployment.
  containerImage: 'drupal:8.9-apache'
  containerPort: 80
  containerReplicas: 1

  # The size of the files directory PVC.
  filesPVCSize: 1Gi
  filesPVCMountPath: /var/www/html/sites/default/files/

  # Ignore creating a files PVC and just use this one.
  # filesPVCName:

  # Settings config map
  settingsConfigMapName: drupal-sample-settings-config-map
  settingsConfigMapMountPath: /var/www/html/sites/default/

  # The size and mount path of the code PVC.
  codePVCSize: 1Gi
  codePVCMountPath: /var/www/html/

  # Ignore creating a code PVC and just use this one.
  # codePVCName:

  # If a code PVC is specified an OpenSSH side car can be created.
  manageSideCar: true
  sideCarImage: ghcr.io/linuxserver/openssh-server
  sideCarEnvironment:
    - name: PUID
      value: '0'
    - name: PGID
      value: '0'
    - name: TZ
      value: US/Pacific
    - name: USER_NAME
      value: root
    - name: PUBLIC_KEY
      value: yourpublickey
  sideCarPort: 2222
  manageSideCarIngress: true
  sideCarHostname: ssh-drupal.localdomain

  # Set this to 'true' to have this operator manage Ingress for the site.
  manageIngress: true
  ingressHostname: drupaldev.localdomain
