## Append samples you want in your CSV to this file as resources ##
resources:
- apps_v1alpha1_drupal.yaml
- apps_v1alpha1_drupaldev.yaml
- apps_v1alpha1_drupalvm.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
