---
- name: Include PVC Tasks
  import_tasks: tasks/pvcs.yml
- name: Include Drupal Tasks
  import_tasks: tasks/drupal.yml
- name: Include Side Car Tasks
  import_tasks: tasks/dev.yml
  when: manage_dev is defined and manage_dev
