---
- name: Include PVC Tasks
  import_tasks: tasks/pvcs.yml
- name: Include Drupal Tasks
  import_tasks: tasks/drupal.yml
- name: Include Side Car Tasks
  import_tasks: tasks/sidecar.yml
  when: manage_side_car is defined and manage_side_car