---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: drupals.apps.dmlb2000.org
spec:
  group: apps.dmlb2000.org
  names:
    kind: Drupal
    listKind: DrupalList
    plural: drupals
    singular: drupal
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Drupal is the Schema for the drupals API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of Drupal
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              containerImage:
                description: Drupal image to deploy.
                type: string
              containerPort:
                type: integer
              filesPVCName:
                type: string
              filesPVCMountPath:
                type: string
              filesPVCSize:
                type: string
              settingsConfigMapName:
                type: string
              settingsConfigMapMountPath:
                type: string
              codePVCName:
                type: string
              codePVCSize:
                type: string
              codePVCMountPath:
                type: string
          status:
            description: Status defines the observed state of Drupal
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
